CONFIG_GPIO=y
CONFIG_MDIO=y
CONFIG_MDIO_GPIO=y

CONFIG_SHELL=y
CONFIG_SHELL_MINIMAL=y
CONFIG_SHELL_TAB=y
CONFIG_SHELL_VT100_COLORS=y
CONFIG_SHELL_TAB_AUTOCOMPLETION=y
CONFIG_SHELL_HISTORY=y
# 20260823 CONFIG_GPIO_SHELL is too big for latest Zephyr
#CONFIG_GPIO_SHELL=y
#CONFIG_MDIO_SHELL=y
CONFIG_SHELL_PROMPT_UART="rtl8305-switch:~$ "
